### ISSUE TITLE
posts page showing incorrect template

### ISSUE THREAD

**Issue by LukaszJaro** [carolinan/fullsiteediting#24]
Hi @carolinan, first just wanted to thank you for your amazing https://fullsiteediting.com resource, it answers so many questions.

I'm using your theme generated site and I wanted to know if this is correct behavior or a bug:

Under reading settings -> Your homepage displays, I set one of my pages to the 'posts page'

![image](https://user-images.githubusercontent.com/10998875/166505574-0183ba23-2c94-42d0-a107-070db7d71df6.png)

When I navigate to my posts page it says its using 'page with sidebar template', however that doesn't appear to be the case, instead it's the index template that is actually being used by the posts page.

![image](https://user-images.githubusercontent.com/10998875/166505486-28ac5369-6ecb-4f6b-a6b7-af82cf050016.png)

I did try some other full site editing themes, and they do in fact show index for the posts page or 'home' template in some cases.

**Comment by carolinan** [comment]
Hi!

The select list in the template section will show the template name if you apply that template before you set the page as the posts page. This also happens in other themes like Twenty Twenty-Two.

I don't know if this is considered a bug or not, but if you think it is a bug, then an issue needs to be opened in the Gutenberg GitHub repository, because it is not a theme issue. The theme does not alter this select list in any way or change the behavior of the posts page.

**Comment by carolinan** [comment]
It might make more sense to not show the template section at all on the posts page, but that would need to be changed in the editor itself.

**Comment by LukaszJaro** [comment]
Thank you, that was very much it..I choose a template beforehand. Please feel free to close this.
