### ISSUE TITLE
global $post is not available in block-pattern-helper.php

### ISSUE THREAD

**Issue by rrjanbiah** [carolinan/fullsiteediting#29]
I'm not able to get the current post ID in https://github.com/carolinan/fullsiteediting/blob/course/Starter%20themes/basic-60/inc/block-pattern-helper.php#L18 using

```php
global $post;
```

Because of this couldn't display different links for different pages (conditional using post ID).

**Comment by carolinan** [comment]
Hi!

Unfortunately we are not able to access globals inside block patterns because the patterns are registered too early. Globals are not available. At least that is my understanding and I really wish there was a solution for it.
This is not an issue with the theme but with how WordPress registers patterns.

**Comment by rrjanbiah** [comment]
Thanks for your quick response. I thought that you have forgot to pass that somewhere. Closing this now.
