### ISSUE TITLE
Site Logo: specify image, and Images in navigation block

### ISSUE THREAD

**Issue by glerner** [carolinan/fullsiteediting#41]
About https://fullsiteediting.com/blocks/site-logo/

The image shown on /blocks/site-logo/ doesn't show the block settings (no block is selected).

There is no documentation on specifying the image for the logo. 
I did find that clicking the "no image" icon in the hover-menu for the block, lets me select an image from Media Library. Not as intuitive as if the setting were in the Block Settings panel. 

I couldn't find how to make the Site Logo appear next to Navigation, other than making columns, so I tried adding the Site Logo as a Navigation entry. That works. 

About the Navigation Block: 
There are no settings for image size of an image included in the Navigation Block menu item. Should be set at the Navigation Block (not each menu item as is currently the way).
When adding an image, the image is placed at the insertion point, so very easy to make the image appear in the middle of the menu text. Hard to see where the insertion point is; so have to press "home" before adding an image.
Images in the menu need to be vertical aligned middle.

Site Logo in a Navigation Block: the logo size is portrait, the navigation icons I'm using are square; the logo needs to have its own size setting in the navigation block

Here's the CSS I used 
```
.wp-block-navigation-item img {
    width: 38px;
    vertical-align: middle;
}
img.custom-logo, .wp-block-navigation-item img.custom-logo {
    width: 100px;
}
.wp-block-navigation ul, .wp-block-navigation ul li {
    row-gap: 5px;
}

```

**Comment by carolinan** [comment]
Hi @glerner!
Did you mean to open an issue in the Gutenberg github repository?

On the website, https://fullsiteediting.com/blocks/site-logo/
The logo image is placed inside a copy of the editor.
So to open and even try out the logo settings, we first have to select the logo block in that editor.

I did not add any context about how to upload the logo image, because the document is intended for developers so that they can see what attributes this block has.

The official user documentation for the site logo can be found here:
https://wordpress.org/documentation/article/site-logo-block/

My page does not currently link to that documentation, because, I have to add all those links manually in my content :) It is taking me some time.

**Comment by glerner** [comment]
Thank you. 
Yes, I will find the Gutenberg repository. I get that you're Documenting full site editing, and they are coding it.

**Comment by carolinan** [comment]
Its my job to do both =D there are already open issues for some of the things you mentioned.
